### ISSUE TITLE
Installation aborted / Permission denied

### ISSUE THREAD

**Issue by urknall** [JWahle/piCoreCDSP#3]
...
# Remove old configuration, in case it was installed before
cat /etc/asound.conf |\
 tr '\n' '\r' |\
  sed 's|\r\r# For more info about this configuration see: https://github.com/scripple/alsa_cdsp\rpcm.camilladsp.*\r}\r# pcm.camilladsp||' |\
   tr '\r' '\n' > /tmp/asound.conf
cat /tmp/asound.conf > /etc/asound.conf
./install_cdsp.sh: line 100: can't create /etc/asound.conf: Permission denied

**Comment by urknall** [comment]
Changed permissions an ran script again, now it finished successfully. Maybe you should take care of asound.conf permissions in your install script.

**Comment by JWahle** [comment]
What did you do before?
What were the permissions (owner,group,permissions) before running the script and to what values did you change it?
The script works, if you use a fresh image.

**Comment by urknall** [comment]
As far as i remember, i made no changes to asound.conf.
The permissions on my system:
tc@piCorePlayer:~$ ls -al /etc/asound.conf 
-rw-r--r--    1 root     root           598 Nov 27 20:37 /etc/asound.conf
to get it running:
chmod 664 /etc/asound.conf
chown root:staff /etc/asound.conf

**Comment by JWahle** [comment]
Okay, thanks.

People occasionally reported this, but I am not sure what causes this.
I suspect changing some setting in the GUI messes with the permissions, but I could not reproduce this.
I'll include the permission change.

**Comment by urknall** [comment]
I will do some tests this week with a fresh picoreplayer installation, but i have the feeling you are right, the reasons are surely configuration changes via the gui...

i forgot to mention, you need to use sudo of course:

sudo chmod 664 /etc/asound.conf
sudo chown root:staff /etc/asound.conf

**Comment by urknall** [comment]
maybe also just adding sudo:

sudo cat /tmp/asound.conf > /etc/asound.conf
sudo echo '
# For more info about this configuration see: https://github.com/scripple/alsa_cdsp

will work

UPDATE: forget that it will not work: user tc is not root but member of staff

**Comment by JWahle** [comment]
Thank you for the suggestion.
I'll see, if I can do it with some special sudo command like [here](https://github.com/JWahle/piCoreCDSP/blob/ef623ad5d58ef682314e51fcebe33298146ab2c2/install_cdsp.sh#L212).
If that doesn't work, I'll just change the permissions.

**Comment by JWahle** [comment]
I just fixed this.
Thank you for the very detailed reporting.

**Comment by urknall** [comment]
Thanks, i was busy this week with work, but i had some short time to do some tests.

On a new picoreplayer installation the old version of your script works, but when you add
bluetooth speakers via the gui, the permissions are changed and the script was not working any more
(no clue, why this is the case, maybe this could be implemented better on picorelayer side, but on
the other hand there is maybe a good reason why the permissions are changed).

Though i could not get camilladsp running this week, it was simply not starting. But that was
after i added bluetooth speakers. I will test again on a new installation without any modifications...

**Comment by JWahle** [comment]
Interesting ...

If you're not sure, why CDSP is not starting, the GUI has a button "Show log file" that should show some information to get you further.

**Comment by urknall** [comment]
Today some more tests, CamillaDSP is running on a fresh picoreplayer installation, after configuring bluetooth outputs via the picoreplayer guy, camilladsp is not running any more. I am not sure if this is only related to asound.conf or iwhen adding bluetooth outputs something else is changed, why its no longer working.

**Comment by urknall** [comment]
Again some more investigation why this is not working for me: the permissions of asound.conf are really only a problem during installation, which you already fixed in your script.

Now i found out, why the camilladsp process is not starting anymore after using bluetooth devices:
the parameter "-C 5" is added automatically to the squeezelite parameters via the pcp gui.
This gives an error when starting camilladsp and there its not starting successfully, when i remove it manually its working again...

**Comment by urknall** [comment]
i spoke to a developer of pcp and he said, this seems like a bug in camilladsp not being able to handle close and open.

**Comment by JWahle** [comment]
The CamillaDSP GUI should be always online.
With the `-C 5` parameter, CamillaDSP should be stopped 5 seconds, after the last audio output (No sound level meters anymore).
However, as soon as you play some audio, it should start again.
If that doesn't work, is there any log output?

Background: CamillaDSP is only running, as long as audio is output to the  `camilladsp` audio device.
Without the `-C 5` parameter, squeezelite continuously outputs audio (silence), even if nothing is played and thus CamillaDSP is running all the time.

**Comment by urknall** [comment]
Thanks for the detailed explanation, now i understand.
I thought the camilladsp process is always running and not only if there is audio output.

I tested it again and its working (tested with 2.0 alpha version), probably also working with 1.0 then.

Thank you very much for your patience and support.
