### ISSUE TITLE
add pyCamillaDSP

### ISSUE THREAD

**Issue by melomane63** [JWahle/piCoreCDSP#4]
pyCamillaDSP is usefull to use remote control. it is necessary for change source or equalizer setting. 

can be possible to add at install script, for the version 2 of camille dsp?

**Comment by JWahle** [comment]
pycamilladsp is already installed.
I added instructions on how to run python scripts using pycamilladsp and pycamilladsp-plot in the section [Running your own python scripts](https://github.com/JWahle/piCoreCDSP#running-your-own-python-scripts).
Does this work for you?

**Comment by melomane63** [comment]
Hello, thanks you for your answer, but i have not the time now for this. Best regards 

Le 7 décembre 2023 18:42:38 GMT+01:00, Johannes Wahle ***@***.***> a écrit :

**Comment by JWahle** [comment]
No problem.
Feel free to reopen this issue or ask on the forums, if you have more questions regarding this.
