### ISSUE TITLE
Connectivity Issues Preventing Installation

### ISSUE THREAD

**Issue by InvisibleFunction** [JWahle/piCoreCDSP#5]
I've tried to run the install over a dozen times today and it seems like it fails downloading a different file every time. I think the problem is whatever is behind repo.picoreplayer.org because it looks like Cloudflare is returning 522 errors:

```
Downloading: e2fsprogs_base-dev.tcz
Connecting to repo.picoreplayer.org (172.67.157.97:443)
wget: server returned error: HTTP/1.1 522
   Error retreiving https://repo.picoreplayer.org/repo/13.x/armv7/tcz/e2fsprogs_base-dev.tcz
FAIL
There was a error downloading compiletc.tcz.
```

At this point I have to reboot to run the script again:
```
tc@stereoPi:~$ ./install_cdsp.sh
Reboot before running the script again.
```

It's too bad I can't try to just download the files that didn't work, because I think they might work at some other time.

I realize that you don't run the repo, but do you have any ideas getting around the issue?

**Comment by InvisibleFunction** [comment]
Of course, I find the answer in the troubleshooting section right after I post 🥇 

Switching to the mirror repo solved my issue.

**Comment by JWahle** [comment]
Glad, I could help so quickly and effortlessly ;)
